version: '3.8'

services:
  better-stack-test:
    build:
      context: .
    container_name: better-stack-test
    ports:
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: better_stack_test
      MYSQL_USER: user
      MYSQL_PASSWORD: local_password
      MYSQL_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: better_stack_test
      MYSQL_USER: user
      MYSQL_PASSWORD: local_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - my-db:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  my-db: